### ISSUE TITLE
Add nested sliders to the main @commongood page

### ISSUE THREAD

**Issue by feeohnah** [studio-cartogram/commongood#2]
Example on staging:
http://alpha.studiocartogram.com/commongood

Each director will have 4 Works added to their post in the form of a relationship field.
The thumbnails from these works will cycle through for each director.
The user should be able to click on any of these thumbnails and be taken to the corresponding video.

**Comment by cartogram** [comment]
@feeohnah i dont understand what you mean by reinitializing magic. this page looks like there is a bunch of broken HTMLin the corder of the image.

**Comment by feeohnah** [comment]
@cartogram there's one missing image, no broken html

**Comment by cartogram** [comment]
The issue still doesn’t make sense

**Comment by feeohnah** [comment]
@cartogram what don't you understand?

**Comment by feeohnah** [comment]
@cartogram I can't figure out how to make the images fill the swiper wrapper height, the img elements already have `object-fit: contain` on them.

http://alpha.studiocartogram.com/commongood
