### ISSUE TITLE
Create a new Single Page for viewing all the Works by one director

### ISSUE THREAD

**Issue by feeohnah** [studio-cartogram/commongood#3]
Something like this:
http://alpha.studiocartogram.com/commongoods/eva-michon

This will contain all the Works that have been added to the director's post.
Previous/Next arrows will cycle through only these 4 works.
Clicking on a thumbnail will bring up that video in the main viewer.

**Comment by feeohnah** [comment]
I'm wondering if there's a way we can accommodate this thumbnail nav as a separate component, like something that fixes to the bottom of the screen, so that we don't have to make too many modifications to the single template.

**Comment by cartogram** [comment]
@feeohnah so, each video will have 2 pages? that is weird

**Comment by feeohnah** [comment]
@cartogram well, I'm open to other suggestions if you can think of a better way to achieve what Jamie is asking for?

**Comment by cartogram** [comment]
What is jamie asking?

**Comment by feeohnah** [comment]
@cartogram got a first pass of this here: http://alpha.studiocartogram.com/works/audi-rs5-slalom

I can’t figure out how to use the non reset post data method for calling custom fields within partial template files. Which means that I can’t exclude the current post from the single page grid of related works.

https://github.com/studio-cartogram/commongood/blob/master/app/themes/commongood-2017/partials/work-related.php
